language: node_js
node_js:
  - "12.3.0"
branches:
  only:
    - master
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//0ejeFhEXkbfR3CgYIARAAGA4SNwF-L9Ir3vP066r1SkpyHykW_-6riRp3IXXR8jGXYBw5D_R1Zkc9r6rp4fGpaLo7HJxllkb4gAA"